import {CATEGORIES, IDEAS, PRODUCTS, VENDORS, USER, IP2LOCATION} from './modules.js'
import {
    PAGE_HOME,
    PAGE_CATEGORIES,
    PAGE_IDEAS,
    PAGE_SERVICE,
    PAGE_VENDOR,
    PAGE_POSTS_SERVICE,
    PAGE_POSTS_SEARCH_VENDOR,
    PAGE_POSTS_PRODUCT,
    PAGE_POSTS_REPORT,
    PAGE_AUTHEN,
    PAGE_NEWS,
} from './pages.js'

export const ACTION_API_ALL      = 'ACTION_API_ALL'
export const ACTION_GET_PC       = 'ACTION_GET_PC'
export const ACTION_DETAIL       = 'ACTION_DETAIL'
export const ACTION_GET_LOCATION = 'ACTION_GET_LOCATION'

export const ACTION_POST_FORGOT_PASSWORD = 'ACTION_POST_FORGOT_PASSWORD'
export const ACTION_POST_LOGIN           = 'ACTION_POST_LOGIN'
export const ACTION_POST_CHANGE_PASSWORD = 'ACTION_POST_CHANGE_PASSWORD'
export const ACTION_POST_CREATE_ACCOUNT  = 'ACTION_POST_CREATE_ACCOUNT'

export const IP2LOCATION_ACTION_GET_LOCATION = IP2LOCATION + '/' + ACTION_GET_LOCATION

export const CATEGORIES_ACTION_API_ALL   = CATEGORIES + '/' + ACTION_API_ALL
export const CATEGORIES_ACTION_GET_PC    = CATEGORIES + '/' + ACTION_GET_PC

export const IDEAS_ACTION_API_ALL        = IDEAS + '/' + ACTION_API_ALL
export const IDEAS_ACTION_DETAIL         = IDEAS + '/' + ACTION_DETAIL

export const PRODUCTS_ACTION_API_ALL     = PRODUCTS + '/' + ACTION_API_ALL
export const PRODUCTS_ACTION_DETAIL      = PRODUCTS + '/' + ACTION_DETAIL

export const VENDORS_ACTION_API_ALL      = VENDORS + '/' + ACTION_API_ALL
export const VENDORS_ACTION_DETAIL       = VENDORS + '/' + ACTION_DETAIL

// user
export const USER_ACTION_DETAIL               = USER + '/' + ACTION_DETAIL
export const USER_ACTION_POST_FORGOT_PASSWORD = USER + '/' + ACTION_POST_FORGOT_PASSWORD
export const USER_ACTION_POST_LOGIN           = USER + '/' + ACTION_POST_LOGIN
export const USER_ACTION_POST_CHANGE_PASSWORD = USER + '/' + ACTION_POST_CHANGE_PASSWORD
export const USER_ACTION_POST_CREATE_ACCOUNT  = USER + '/' + ACTION_POST_CREATE_ACCOUNT

export const ACTION_GET_IDEAS    = 'ACTION_GET_IDEAS'
export const ACTION_GET_SERVICES = 'ACTION_GET_SERVICES'
export const ACTION_GET_IMAGES   = 'ACTION_GET_IMAGES'
export const ACTION_GET_IMAGE    = 'ACTION_GET_IMAGE'
export const ACTION_GET_SERVICE  = 'ACTION_GET_SERVICE'
export const ACTION_GET_VENDOR   = 'ACTION_GET_VENDOR'
export const ACTION_GET_PAGE     = 'ACTION_GET_PAGE'
export const ACTION_GET_NEWS     = 'ACTION_GET_NEWS'

//
export const ACTION_GET_CITY       = 'ACTION_GET_CITY'
export const ACTION_GET_DISTRICT   = 'ACTION_GET_DISTRICT'
export const ACTION_SEARCH_ADDRESS = 'ACTION_SEARCH_ADDRESS'
export const ACTION_POST_SERVICE   = 'ACTION_POST_SERVICE'

// vendor
export const ACTION_GET_VENDOR_SERVICES = 'ACTION_GET_VENDOR_SERVICES'
export const ACTION_GET_VENDOR_NEWS     = 'ACTION_GET_VENDOR_NEWS'
export const ACTION_GET_VENDOR_GALLERY  = 'ACTION_GET_VENDOR_GALLERY'
export const ACTION_GET_VENDOR_PROJECTS = 'ACTION_GET_VENDOR_PROJECTS'
export const ACTION_GET_VENDOR_RATING   = 'ACTION_GET_VENDOR_RATING'

// news
// export const ACTION_GET_NEWS = 'ACTION_GET_NEWS'
// export const ACTION_GET_PAGE = 'ACTION_GET_PAGE'
export const ACTION_SERVICES_CATEGORY = 'ACTION_SERVICES_CATEGORY'
export const ACTION_SERVICES_RELATED  = 'ACTION_SERVICES_RELATED'
export const ACTION_PRODUCTS_CATEGORY = 'ACTION_PRODUCTS_CATEGORY'
export const ACTION_PRODUCTS_RELATED  = 'ACTION_PRODUCTS_RELATED'

// PAGE_HOME
export const PAGE_HOME_ACTION_GET_IDEAS    = PAGE_HOME + '/' + ACTION_GET_IDEAS
export const PAGE_HOME_ACTION_GET_SERVICES = PAGE_HOME + '/' + ACTION_GET_SERVICES
export const PAGE_HOME_ACTION_GET_PAGE     = PAGE_HOME + '/' + ACTION_GET_PAGE
export const PAGE_HOME_ACTION_GET_NEWS     = PAGE_HOME + '/' + ACTION_GET_NEWS

// PAGE_IDEAS
export const PAGE_IDEAS_ACTION_GET_IMAGES = PAGE_IDEAS + '/' + ACTION_GET_IMAGES
export const PAGE_IDEAS_ACTION_GET_IMAGE  = PAGE_IDEAS + '/' + ACTION_GET_IMAGE
export const PAGE_IDEAS_ACTION_GET_PAGE   = PAGE_IDEAS + '/' + ACTION_GET_PAGE

// PAGE_CATEGORIES
export const PAGE_CATEGORIES_ACTION_GET_SERVICES = PAGE_CATEGORIES + '/' + ACTION_GET_SERVICES
export const PAGE_CATEGORIES_ACTION_GET_LOCATION = PAGE_CATEGORIES + '/' + ACTION_GET_LOCATION
export const PAGE_CATEGORIES_ACTION_GET_PAGE     = PAGE_CATEGORIES + '/' + ACTION_GET_PAGE

// PAGE_SERVICE
export const PAGE_SERVICE_ACTION_GET_SERVICE         = PAGE_SERVICE + '/' + ACTION_GET_SERVICE
export const PAGE_SERVICE_ACTION_GET_VENDOR_SERVICES = PAGE_SERVICE + '/' + ACTION_GET_VENDOR_SERVICES
export const PAGE_SERVICE_ACTION_GET_VENDOR_NEWS     = PAGE_SERVICE + '/' + ACTION_GET_VENDOR_NEWS
export const PAGE_SERVICE_ACTION_GET_VENDOR_GALLERY  = PAGE_SERVICE + '/' + ACTION_GET_VENDOR_GALLERY
export const PAGE_SERVICE_ACTION_GET_VENDOR_PROJECTS = PAGE_SERVICE + '/' + ACTION_GET_VENDOR_PROJECTS
export const PAGE_SERVICE_ACTION_GET_PAGE            = PAGE_SERVICE + '/' + ACTION_GET_PAGE
export const PAGE_SERVICE_ACTION_GET_VENDOR_RATING   = PAGE_SERVICE + '/' + ACTION_GET_VENDOR_RATING

// PAGE_VENDOR
export const PAGE_VENDOR_ACTION_GET_VENDOR          = PAGE_VENDOR + '/' + ACTION_GET_VENDOR
export const PAGE_VENDOR_ACTION_GET_VENDOR_SERVICES = PAGE_VENDOR + '/' + ACTION_GET_VENDOR_SERVICES
export const PAGE_VENDOR_ACTION_GET_VENDOR_NEWS     = PAGE_VENDOR + '/' + ACTION_GET_VENDOR_NEWS
export const PAGE_VENDOR_ACTION_GET_VENDOR_GALLERY  = PAGE_VENDOR + '/' + ACTION_GET_VENDOR_GALLERY
export const PAGE_VENDOR_ACTION_GET_VENDOR_PROJECTS = PAGE_VENDOR + '/' + ACTION_GET_VENDOR_PROJECTS
export const PAGE_VENDOR_ACTION_GET_VENDOR_RATING   = PAGE_VENDOR + '/' + ACTION_GET_VENDOR_RATING
export const PAGE_VENDOR_ACTION_GET_PAGE            = PAGE_VENDOR + '/' + ACTION_GET_PAGE

// PAGE_POSTS
export const PAGE_POSTS_SERVICE_ACTION_GET_CITY       = PAGE_POSTS_SERVICE + '/' + ACTION_GET_CITY
export const PAGE_POSTS_SERVICE_ACTION_GET_DISTRICT   = PAGE_POSTS_SERVICE + '/' + ACTION_GET_DISTRICT
export const PAGE_POSTS_SERVICE_ACTION_SEARCH_ADDRESS = PAGE_POSTS_SERVICE + '/' + ACTION_SEARCH_ADDRESS
export const PAGE_POSTS_SERVICE_ACTION_POST_SERVICE   = PAGE_POSTS_SERVICE + '/' + ACTION_POST_SERVICE

// PAGE_NEWS
export const PAGE_NEWS_ACTION_GET_NEWS          = PAGE_NEWS + '/' + ACTION_GET_NEWS
export const PAGE_NEWS_ACTION_GET_PAGE          = PAGE_NEWS + '/' + ACTION_GET_PAGE
export const PAGE_NEWS_ACTION_SERVICES_CATEGORY = PAGE_NEWS + '/' + ACTION_SERVICES_CATEGORY
export const PAGE_NEWS_ACTION_SERVICES_RELATED  = PAGE_NEWS + '/' + ACTION_SERVICES_RELATED
export const PAGE_NEWS_ACTION_PRODUCTS_CATEGORY = PAGE_NEWS + '/' + ACTION_PRODUCTS_CATEGORY
export const PAGE_NEWS_ACTION_PRODUCTS_RELATED  = PAGE_NEWS + '/' + ACTION_PRODUCTS_RELATED