import {CATEGORIES, IDEAS, PRODUCTS, VENDORS} from './modules.js';

export const ACTION_API_ALL      = 'ACTION_API_ALL'
export const ACTION_GET_PC       = 'ACTION_GET_PC'
export const ACTION_DETAIL       = 'ACTION_DETAIL'
export const ACTION_GET_LOCATION = 'ACTION_GET_LOCATION'

export const ACTION_POST_FORGOT_PASSWORD = 'ACTION_POST_FORGOT_PASSWORD'
export const ACTION_POST_LOGIN           = 'ACTION_POST_LOGIN'
export const ACTION_POST_CHANGE_PASSWORD = 'ACTION_POST_CHANGE_PASSWORD'
export const ACTION_POST_CREATE_ACCOUNT  = 'ACTION_POST_CREATE_ACCOUNT'

export const ACTION_GET_IDEAS    = 'ACTION_GET_IDEAS'
export const ACTION_GET_SERVICES = 'ACTION_GET_SERVICES'
export const ACTION_GET_IMAGES   = 'ACTION_GET_IMAGES'
export const ACTION_GET_IMAGE    = 'ACTION_GET_IMAGE'
export const ACTION_GET_SERVICE  = 'ACTION_GET_SERVICE'
export const ACTION_GET_VENDOR   = 'ACTION_GET_VENDOR'
export const ACTION_GET_PAGE     = 'ACTION_GET_PAGE'
export const ACTION_GET_NEWS     = 'ACTION_GET_NEWS'

//
export const ACTION_GET_CITY       = 'ACTION_GET_CITY'
export const ACTION_GET_DISTRICT   = 'ACTION_GET_DISTRICT'
export const ACTION_SEARCH_ADDRESS = 'ACTION_SEARCH_ADDRESS'
export const ACTION_POST_SERVICE   = 'ACTION_POST_SERVICE'

// vendor
export const ACTION_GET_VENDOR_SERVICES = 'ACTION_GET_VENDOR_SERVICES'
export const ACTION_GET_VENDOR_NEWS     = 'ACTION_GET_VENDOR_NEWS'
export const ACTION_GET_VENDOR_GALLERY  = 'ACTION_GET_VENDOR_GALLERY'
export const ACTION_GET_VENDOR_PROJECTS = 'ACTION_GET_VENDOR_PROJECTS'
export const ACTION_GET_VENDOR_RATING   = 'ACTION_GET_VENDOR_RATING'

// news
// export const ACTION_GET_NEWS = 'ACTION_GET_NEWS'
// export const ACTION_GET_PAGE = 'ACTION_GET_PAGE'
export const ACTION_SERVICES_CATEGORY = 'ACTION_SERVICES_CATEGORY'
export const ACTION_SERVICES_RELATED  = 'ACTION_SERVICES_RELATED'
export const ACTION_PRODUCTS_CATEGORY = 'ACTION_PRODUCTS_CATEGORY'
export const ACTION_PRODUCTS_RELATED  = 'ACTION_PRODUCTS_RELATED'